### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by azenetheafr** [andrewrk/truthfinder#1]
I want to use [Sourcegraph](https://sourcegraph.com) for truthfinder code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/andrewrk/truthfinder. (It should only take 30 seconds.)

Thank you!

**Comment by andrewrk** [comment]
done. btw this project is pretty much abandoned.
